cabal-version:      3.0
name:               duraflow
version:            0.1.0.0
synopsis:           Durable local workflows
category:           System
description:        Haskell library scaffold for local durable workflows.
license:            NONE
build-type:         Simple
extra-source-files: README.md

common defaults
  default-language: GHC2021
  ghc-options:      -Wall -Wcompat
  build-depends:    base >=4.18 && <5

library
  import:           defaults
  hs-source-dirs:   src
  exposed-modules:
      Duraflow
    , Duraflow.Internal.Snapshot
    , Duraflow.Internal.Storage
    , Duraflow.Internal.Types
  build-depends:
      aeson      ^>=2.2.5.1
    , bytestring ^>=0.12.2.0
    , directory  ^>=1.3.8.5
    , filepath   ^>=1.5.4.0
    , filelock   ^>=0.1.1.9
    , text       ^>=2.1.3
    , unix       ^>=2.8.7.0

test-suite duraflow-test
  import:           defaults
  type:             exitcode-stdio-1.0
  hs-source-dirs:   test
  main-is:          Main.hs
  other-modules:
      SnapshotTests
    , StorageTests
    , TestSupport
  build-depends:
      aeson      ^>=2.2.5.1
    , bytestring ^>=0.12.2.0
    , directory  ^>=1.3.8.5
    , duraflow
    , filepath   ^>=1.5.4.0
    , filelock   ^>=0.1.1.9
    , text       ^>=2.1.3
    , unix       ^>=2.8.7.0
